
apiVersion: v1
kind: Pod
metadata:
  name: host2
  labels:
    l2sm/app: host2
    l2sm: "true"
  annotations:
    l2sm/networks: '[{"name": "ztna-example-1-portscan", "ips": ["10.0.0.2/24"]}]'
spec:
  containers:
  - name: alpine
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine:latest
