apiVersion: v1
kind: Pod
metadata:
  name: ned
  labels:
    app: l2sm
spec:
  hostNetwork: true
  containers:
  - name: mycontainer
    image: alexdecb/l2sm-switch:2.2
    command: ["sleep", "infinity"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]