apiVersion: v1
kind: Pod
metadata:
  name: ned
  labels:
    app: l2sm
spec:
  hostNetwork: true
  initContainers:
      - name: wait-for-l2sm-operator
        image: curlimages/curl
        args:
        - /bin/sh
        - -c
        - >
          set -x;
          while [ $(curl -sw '%{http_code}' "http://l2sm-operator-service:8080/healthz" -o /dev/null) -ne 200 ]; do
            sleep 15;
          done;
          sleep 5;
  containers:
  - name: mycontainer
    image: alexdecb/l2sm-switch:2.2
    command: ["sleep", "infinity"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  nodeSelector:
    dedicated: master