
apiVersion: v1
kind: Pod
metadata:
  name: host2
  labels:
    l2sm/app: host2
    l2sm: "true"
  annotations:
    l2sm/networks: ztna-example-1-portscan
spec:
  containers:
  - name: alpine
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine:latest