apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-l2sm-arm
spec:
  replicas: 2
  selector:
    matchLabels:
      test: pyra
  template:
    metadata:
      labels:
        test: pyra
      annotations:
        l2sm.k8s.conf.io/virtual-networks: my-first-network, my-second-network
    spec:
      containers: 
      - name: ping-arm
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: alpine:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      nodeName: pyra
