apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-l2sm-amd
spec:
  replicas: 4
  selector:
    matchLabels:
      test: rex
  template:
    metadata:
      labels:
        test: rex
      annotations:
        l2sm.k8s.conf.io/virtual-networks: my-first-network
    spec:
      containers: 
      - name: ping-amd
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: alpine:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      nodeName: rex
