apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/name: mutatingwebhookconfiguration
    app.kubernetes.io/instance: mutating-webhook-configuration
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: controllermanager
    app.kubernetes.io/part-of: controllermanager
    app.kubernetes.io/managed-by: kustomize
  name: mutating-webhook-configuration
webhooks:
  - name: mpod.kb.io
    clientConfig:
      url: https://192.168.122.60:9443/mutate-v1-pod
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIVENDQWdXZ0F3SUJBZ0lVSFo1SkszNmRERnJHclJ5b0RlYlFSeTVZdXZNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dERVdNQlFHQTFVRUF3d05iRzlqWVd3dGQyVmlhRzl2YXpBZUZ3MHlOREE1TVRjeE1qSTNNRFZhRncweQpOVEE1TVRjeE1qSTNNRFZhTUJneEZqQVVCZ05WQkFNTURXeHZZMkZzTFhkbFltaHZiMnN3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURXWGFjZ3B3K3prMlFSb1YvdVhuMldNZ0xGczZuckZGU0YKdUVKSXBFb3p3UTZJTnZNeTN6RDFVM0ptQlZ2K2NLL1N5bmJNMFdnUE95blhaVU9qTXJUVncwak9ZNjNFVkdJUQoyZW5CeXdXUGZHd1BQZDdKYzk2REZJVzRIY3VvVlJaOFpMei91UmZxQ2J6VElEVG80WUFBbE05TzgyTWpQUHIyCkpTSTBJbkpsbi9IdWtPTlB4MUNYZU14UVdIWGZEcUNWMTBUWU5oNjhUNHUxKzQ5V2E3MGVmQmtsSW1XT3crTnkKT3RxOC9nV28ySTQvaDBnVkRqN3V4VEVWblgrU2NvdUE3eW90SDhwMi9aZmcxQkRaYzAwdXRVSm42ZVZaQzYyWgpTWnFSRWlwV0RSenNidXY5cmppUkxGV3A0VzVvcFpMUUVvUFMyV3VxL1NKZEY5UENUZkViQWdNQkFBR2pYekJkCk1EWUdBMVVkRVFRdk1DMkhCSDhBQUFHSEJNQ29lanlDQ1d4dlkyRnNhRzl6ZElJVWQyVmlhRzl2YXkxelpYSjIKWlhJdWJHOWpZV3d3RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlcxVUlSbXRFUDY0aEUwOEpPWCtrbDlxTFhFb2IyVDE5TTh4ODV6VCtoCnVvMm8vN3Ztd2ZHTmhmZ25PT0o2eXUxSzhUM2RSeDdza0RybUNYWFdpV3l2M25DeGIwcUo1WUtBWkNaNGZvdTUKejZkMUVnelphTUJsMFZpL01KMDRNemV6MnNtSXN1QzA1c1doWjVDVDhCNGVjM1hFdlFJOTZ5QUhYL1Rjd2hMeQpzZWN1c1QyZDRlUldjSEVCR3NEUnhlejdEcU85UUl0T3JaR0htWHlnOC83cjFTTUhhTmFyMWU4QTY4bVEvZiszCjFyUkowVUF6MWRrK09JUkFPNmM5eVRoTUdVdzJwbklkcVRSTWRiWERMSVdLb1FQM0Y1RXh0bG5lajg5S3F0TXoKc0JkVEUrWHVUTWtGais3UTRZbk1WQ3BBdTNVOUtueHVVaGFvblcrdkhyOU4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1"]
    objectSelector:
      matchLabels:
        l2sm: "true"
