---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - l2smnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - l2smnetworks/finalizers
  verbs:
  - update
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - l2smnetworks/status
  verbs:
  - get
  - patch
  - update
