apiVersion: v1
kind: ConfigMap
metadata:
  name: node-c-config
data:
  config.json: |
    {
      "Nodename": "NodeA",
      "MetricsNeighbourNodes": [
         {
               "name": "NodeA",
               "ip": "10.0.2.2",
               "jitterInterval": 10,
               "throughputInterval": 20,
               "rttInterval": 3
         },
         {
               "name": "NodeB",
               "ip": "10.0.2.4",
               "rttInterval": 20,
               "throughputInterval": 20,
         }
      ]
   }