apiVersion: v1
kind: ConfigMap
metadata:
  name: node-a-config
data:
  config.json: |
    {
      "Nodename": "NodeA",
      "MetricsNeighbourNodes": [
         {
               "name": "NodeB",
               "ip": "10.0.2.4",
               "jitterInterval": 10,
               "throughputInterval": 20,
               "rttInterval": 3
         },
         {
               "name": "NodeC",
               "ip": "10.0.2.6",
               "rttInterval": 20,
               "throughputInterval": 20,
         }
      ]
   }