apiVersion: v1
kind: ConfigMap
metadata:
  name: node-b-config
data:
  config.json: |
    {
      "Nodename": "NodeB",
      "MetricsNeighbourNodes": [
         {
               "name": "NodeA",
               "ip": "10.0.2.2",
               "jitterInterval": 10,
               "throughputInterval": 20,
         },
         {
               "name": "NodeC",
               "ip": "10.0.2.6",
               "rttInterval": 20,
               "jitterInterval": 20,
         }
      ]
   }