{{- range .Values.global.nodes }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-lpm
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{ .name }}-lpm
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
---
{{- end }}
