apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: l2sm-networks.l2sm.k8s.local
spec:
  group: l2sm.k8s.local
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                config:
                  type: string 
                  nullable: true
                signature:
                  type: string
                  nullable: true
            status:
              type: object
              properties:
                connectedPods:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: l2sm-networks
    singular: l2sm-network
    kind: L2SMNetwork
    shortNames:
      - l2sm-net
