apiVersion: v1
kind: Pod
metadata:
  name: pod-pyra
  annotations:
    k8s.v1.cni.cncf.io/networks: my-second-network
spec:
  containers: 
  - name: pod-pyra
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  nodeName: pyra
