apiVersion: v1
kind: Pod
metadata:
  name: pod-pyra-2
#  annotations:
#    k8s.v1.cni.cncf.io/networks: vpod1@vpod1
spec:
  containers: 
  - name: pod-pyra-2
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: lewisfelix24/testing-pod:rpi
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  nodeName: pyra
