apiVersion: v1
kind: Pod
metadata:
  name: ping
  annotations:
   k8s.v1.cni.cncf.io/networks: '[{"name": "veth10","ips": ["10.0.0.6/24"]}]'
spec:
  containers:
  - name: router
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  # Use this parameter if you want to place the pod in a specific node
  nodeName: ant-machine
