#-------------------------------------------------------------------------------
# Copyright 2024  Charles III University of Madrid
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.
# 
# SPDX-License-Identifier: Apache-2.0
#-------------------------------------------------------------------------------
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: l2sm-switch
  #namespace: kube-system
  labels:
    l2sm-component: l2sm-switch
spec:
  selector:
    matchLabels:
      l2sm-component: l2sm-switch
  template:
    metadata:
      labels:
        l2sm-component: l2sm-switch
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "veth1", "ips": ["fe80::58d0:b8ff:fe42:debf/64"]}, { "name": "veth2", "ips": ["fe80::58d0:b8ff:fe42:debe/64"]}, { "name": "veth3", "ips": ["fe80::58d0:b8ff:fe42:debd/64"]}, { "name": "veth4", "ips": ["fe80::58d0:b8ff:fe42:debc/64"]}, { "name": "veth5", "ips": ["fe80::58d0:b8ff:fe42:debb/64"]}, { "name": "veth6", "ips": ["fe80::58d0:b8ff:fe42:deba/64"]}, { "name": "veth7", "ips": ["fe80::58d0:b8ff:fe42:deb9/64"]}, { "name": "veth8", "ips": ["fe80::58d0:b8ff:fe42:deb8/64"]}, { "name": "veth9", "ips": ["fe80::58d0:b8ff:fe42:deb7/64"]}, { "name": "veth10", "ips": ["fe80::58d0:b8ff:fe42:deb6/64"]}]'
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      # initContainers:
      # - name: wait-for-l2sm-operator
      #   image: curlimages/curl
      #   args:
      #   - /bin/sh
      #   - -c
      #   - >
      #     set -x;
      #     while [ $(curl -sw '%{http_code}' "http://l2sm-operator-service:8080/healthz" -o /dev/null) -ne 200 ]; do
      #       sleep 15;
      #     done;
      #     sleep 5;
      containers:
      - name: l2sm-switch
        image: alexdecb/l2sm-switch:2.2
        #args: ["setup_switch.sh && sleep infinity"]
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NVETHS
          value: "10"  
        - name: CONTROLLERIP
          value: "l2sm-controller-service"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      nodeSelector:
        kubernetes.io/arch: amd64

