apiVersion: v1
kind: Pod
metadata:
  name: mysql-development-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    envFrom:
    - secretRef:
        name: mysql-secret
    ports:
      - containerPort: 3306
        name: mysql
    volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
      - name: initdb-volume
        mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
    - name: initdb-volume
      configMap:
        name: mysql-schema
        items:
        - key: init.sql
          path: init.sql
  nodeName: l2sm1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-development-service
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001
      protocol: TCP
  selector:
    app: mysql

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded "password"
  MYSQL_USER: bDJzbQ==              # Base64 encoded "l2sm"
  MYSQL_PASSWORD: bDJzbQ==          # Base64 encoded "l2sm"
  MYSQL_DATABASE: bDJzbQ==
