apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.network.name}}-topology-manager-binding
subjects:
  - kind: ServiceAccount
    name: {{.Values.global.network.name}}-sa
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.global.network.name}}-topology-manager
  apiGroup: rbac.authorization.k8s.io
