apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-{{.Values.global.network.name}}
  namespace: {{ $.Values.global.namespace }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets:
        {{- range $index, $elem := $.Values.global.nodes }}
          - {{$elem.name}}-lpm:8090
        {{- end }}