# This rule is not used by the project controllermanager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the l2sm.l2sm.k8s.local.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controllermanager
    app.kubernetes.io/managed-by: kustomize
  name: ccipsoverlay-editor-role
rules:
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - ccipsoverlays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - ccipsoverlays/status
  verbs:
  - get
