# permissions for end users to view networkedgedevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: networkedgedevice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: l2network
    app.kubernetes.io/part-of: l2network
    app.kubernetes.io/managed-by: kustomize
  name: networkedgedevice-viewer-role
rules:
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - networkedgedevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - networkedgedevices/status
  verbs:
  - get
