---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - ccipsoverlays
  - l2networks
  - networkedgedevices
  - overlays
  - quarantinepodrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - ccipsoverlays/finalizers
  - l2networks/finalizers
  - networkedgedevices/finalizers
  - overlays/finalizers
  - quarantinepodrequests/finalizers
  verbs:
  - update
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - ccipsoverlays/status
  - l2networks/status
  - networkedgedevices/status
  - overlays/status
  - quarantinepodrequests/status
  verbs:
  - get
  - patch
  - update
