apiVersion: v1
kind: Pod
metadata:
  name: pong
  labels:
    app: test2
  annotations:
    k8s.v1.cni.cncf.io/networks: first-network
spec:
  containers:
  - name: router
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  # Use this parameter if you want to place the pod in a specific node
  nodeName: l2sm2
