apiVersion: v1
kind: Pod
metadata:
  name: pod-rex
  annotations:
    l2sm.k8s.conf.io/virtual-networks: my-first-network, my-second-network, my-third-network
spec:
  containers: 
  - name: pod-rex
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  nodeName: rex
