apiVersion: l2sm.l2sm.k8s.local/v1
kind: Overlay
metadata:
  name: overlay-sample
spec:
  topology:
    nodes:
      - l2sm1
      - l2sm2
    links:
      - endpointA: l2sm1
        endpointB: l2sm2
  switchTemplate:
    spec:
      containers:
        - name: l2sm-switch
          image: alexdecb/l2sm-switch:2.7
          resources: {}
          env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NVETHS
            value: "10"  
          - name: CONTROLLERIP
            value: "l2sm-controller-service"
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 80