apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtual-networks.l2sm.k8s.conf.io
spec:
  group: l2sm.k8s.conf.io
  scope: Namespaced
  names:
    plural: virtual-networks
    singular: virtual-network
    kind: VirtualNetwork
    shortNames:
    - virt-net
    - vn
  versions:
    -  name: v1
       served: true
       storage: true
       schema:
         openAPIV3Schema:
           type: object
           required:
           - kind
           - spec
           properties:
             apiVersion:
               type: string
             kind:
               type: string
             metadata:
               type: object
             spec:
               type: object
               required:
               - name
               properties: 
                 name:
                   type: string
                 config:
                   type: string
