apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sample-inter-network
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "l2sm",
      "device": "l2sm-vNet",
      "kind": {
        "inter": {
          "provider": {
            "name": "<idco-name>",
            "domain": "<domain-name>"
          },
          "accessList": ["<public-key-1>","<public-key-2>",...,"<public-key-N>"] 
          ]
        }
      }
    }'
