  apiVersion: apps/v1
   kind: Deployment
   metadata:
   name: node-c-lpm
   spec:
   replicas: 1
   selector:
      matchLabels:
         app: node-c-lpm
   template:
      metadata:
         labels:
         app: node-c-lpm
      spec:
         containers:
         - name: lpm-container
         image: alexdecb/net_exporter:latest
         workingDir: /usr/src/app
         securityContext:
            capabilities:
               add: ["NET_ADMIN"]
         ports:
         - containerPort: 8090  
         volumeMounts:
         - name: config-volume
            mountPath: /usr/src/app/config.json
            subPath: config.json
         volumes:
         - name: config-volume
         configMap:
            name: node-c-config
   ---
   apiVersion: v1
   kind: Service
   metadata:
   name: node-c-lpm
   spec:
   selector:
      app: node-c-lpm
   ports:
      - protocol: TCP
         port: 8090
         targetPort: 8090