apiVersion: apps/v1
kind: Deployment
metadata:
  name: l2sm-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      l2sm-component: l2sm-opt
  template:
    metadata:
      labels:
        l2sm-component: l2sm-opt
    spec:
      serviceAccountName: l2sm-operator
      initContainers:
      - name: wait-for-l2sm-controller
        image: curlimages/curl
        args:
        - /bin/sh
        - -c
        - >
          set -x;
          while [ $(curl -sw '%{http_code}' "http://l2sm-controller-service:8181/onos/ui" -o /dev/null) -ne 302 ]; do
            sleep 15;
          done;
          sleep 5;
      containers:
      - image: alexdecb/l2sm-operator:2.4
        name: l2sm-opt-pod
        env:
          - name: CONTROLLER_IP
            value: l2sm-controller-service
          - name: DATABASE_IP
            value: mysql-development-service
          - name: MYSQL_USER
            value: l2sm
          - name: MYSQL_PASSWORD
            value: l2sm
          - name: MYSQL_DATABASE
            value: l2sm
        # imagePullPolicy: Always
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule
        
---
apiVersion: v1
kind: Service
metadata:
  name: l2sm-operator-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    l2sm-component: l2sm-opt


