apiVersion: apps/v1
kind: Deployment
metadata:
  name: l2sm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: l2sm-controller
  template:
    metadata:
      labels:
        app: l2sm-controller
    spec:
      containers:
      - name: l2sm-controller
        image: alexdecb/l2sm-controller:2.4
        readinessProbe:
          httpGet:
            path: /onos/ui
            port: 8181   
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 6633
        - containerPort: 8181
        # imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: l2sm-controller-service
spec:
  selector:
    app: l2sm-controller
  ports:
  - name: of13-port
    protocol: TCP
    port: 6633
    targetPort: 6633
  - name: http-port
    protocol: TCP
    port: 8181
    targetPort: 8181
  type: ClusterIP
