apiVersion: apps/v1
kind: Deployment
metadata:
  name: l2sm-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      l2sm-component: l2sm-opt
  template:
    metadata:
      labels:
        l2sm-component: l2sm-opt
    spec:
      serviceAccountName: l2sm-operator
      initContainers:
      - name: wait-for-l2sm-controller
        image: busybox:1.31
        command: ["/bin/sh", "-c", "set -x; while true; do status_code=$(wget --spider -S http://l2sm-controller-service:8181/onos/ui 2>&1 | grep 'HTTP/' | awk '{print $2}'); [ -z $status_code ] && sleep 15 || [ $status_code -eq 200 ] && break || sleep 15; done"]     
      containers:
      - name: wait-test
        image: busybox:1.31
        command: ["sleep","infinity"]
      - image: alexdecb/l2sm-operator:2.2
        name: l2sm-opt-pod
        env:
          - name: CONTROLLER_IP
            value: l2sm-controller-service
      - image: mysql/mysql-server:5.7
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: L2SM
          - name: MYSQL_USER
            value: l2sm
          - name: MYSQL_PASSWORD
            value: l2sm;
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule
