apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-a-lpm
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-a-lpm
  template:
    metadata:
      labels:
        app: node-a-lpm
    spec:
      hostNetwork: true
      containers:
      - name: node-a-lpm-container
        image: alexdecb/net_exporter:latest
        workingDir: /usr/src/app
        ports:
        - containerPort: 8090  
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src/app/config.json
          subPath: config.json
      volumes:
      - name: config-volume
        configMap:
          name: node-a-config
---
apiVersion: v1
kind: Service
metadata:
  name: node-a-lpm
  namespace: prometheus
spec:
  selector:
    app: node-a-lpm
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090