apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: l2-ps
  #namespace: kube-system
  labels:
    l2sm-component: l2-ps
spec:
  selector:
    matchLabels:
      l2sm-component: l2-ps
  template:
    metadata:
      labels:
        l2sm-component: l2-ps
      annotations:
        k8s.v1.cni.cncf.io/networks: vhost1@vhost1, vhost2@vhost2, vhost3@vhost3, vhost4@vhost4, vhost5@vhost5, vhost6@vhost6, vhost7@vhost7, vhost8@vhost8, vhost9@vhost9, vhost10@vhost10
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: l2-ps
        image: alexdecb/l2sm-ovs:test
        command: ["sleep","infinity"]
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NVPODS
          value: "10"  
        - name: CONTROLLERIP
          value: "l2sm-controller-service"

        imagePullPolicy: Always
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      nodeSelector:
        kubernetes.io/arch: amd64
