apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: l2-ps-arm64
  #namespace: kube-system
  labels:
    l2sm-component: l2-ps
spec:
  selector:
    matchLabels:
      l2sm-component: l2-ps
  template:
    metadata:
      labels:
        l2sm-component: l2-ps
      annotations:
        k8s.v1.cni.cncf.io/networks: vhost1@vhost1, vhost2@vhost2, vhost3@vhost3, vhost4@vhost4, vhost5@vhost5, vhost6@vhost6, vhost7@vhost7, vhost8@vhost8, vhost9@vhost9, vhost10@vhost10, vxlan1@vxlan1, vxlan2@vxlan2, vxlan3@vxlan3, vxlan4@vxlan4, vxlan5@vxlan5, vxlan6@vxlan6, vxlan7@vxlan7, vxlan8@vxlan8, vxlan9@vxlan9, vxlan10@vxlan10
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: l2-ps
        image: lewisfelix24/l2sm-ovs:latest
        command: ["/bin/sh", "-c"]
        args: ["ovsdb-server --remote=punix:/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options --pidfile=/var/run/openvswitch/ovsdb-server.pid 
         --detach && ovs-vsctl --db=unix:/var/run/openvswitch/db.sock --no-wait init && ovs-vswitchd --pidfile=/var/run/openvswitch/ovs-vswitchd.pid --detach && 
         ip link set vhost1 up && ip link set vhost2 up && ip link set vhost3 up && ip link set vhost4 up && ip link set vhost5 up && ip link set vhost6 up && ip link set vhost7 up && ip link set vhost8 up && 
         ip link set vhost9 up && ip link set vhost10 up && ip link set vxlan1 up && ip link set vxlan2 up && ip link set vxlan3 up && ip link set vxlan4 up && ip link set vxlan5 up && ip link set vxlan6 up && 
         ip link set vxlan7 up && ip link set vxlan8 up && ip link set vxlan9 up && ip link set vxlan10 up && 
         ovs-vsctl add-br brtun && ip link set brtun up &&
         ovs-vsctl add-port brtun vhost1 && ovs-vsctl add-port brtun vhost2 && ovs-vsctl add-port brtun vhost3 && ovs-vsctl add-port brtun vhost4 && ovs-vsctl add-port brtun vhost5 &&
         ovs-vsctl add-port brtun vhost6 && ovs-vsctl add-port brtun vhost7 && ovs-vsctl add-port brtun vhost8 && ovs-vsctl add-port brtun vhost9 && ovs-vsctl add-port brtun vhost10 &&
         ovs-vsctl add-port brtun vxlan1 && ovs-vsctl add-port brtun vxlan2 && ovs-vsctl add-port brtun vxlan3 && ovs-vsctl add-port brtun vxlan4 && ovs-vsctl add-port brtun vxlan5 &&
         ovs-vsctl add-port brtun vxlan6 && ovs-vsctl add-port brtun vxlan7 && ovs-vsctl add-port brtun vxlan8 && ovs-vsctl add-port brtun vxlan9 && ovs-vsctl add-port brtun vxlan10 &&
         /bin/sleep 3650d"]
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      nodeSelector:
        kubernetes.io/arch: arm64
