apiVersion: v1
kind: Pod
metadata:
  name: cdn-server
  labels:
    app: test4
  annotations:
    l2sm/networks: '[{"name": "v-network-1", "ips":["192.168.1.8/24"]}]'
spec:
  containers:
  - name: server
    command: ["/bin/ash", "-c", "sleep infinity & wait"]
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  #nodeName: test-l2sm-uc3m-polito-1
