# Copyright 2024 Universidad Carlos III de Madrid
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: cdn-server
  labels:
    app: test4
    l2sm: "true"
  annotations:
    l2sm/networks: '[{"name": "v-network-1", "ips":["10.0.1.2/24"]}]'
spec:
  containers:
  - name: server
    command: ["/bin/ash", "-c", "ip route add 10.0.2.0/24 via 10.0.1.1 dev net1 && trap : TERM INT; sleep infinity & wait"]    
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  nodeName: test-l2sm-uc3m-polito-1
