apiVersion: v1
kind: Pod
metadata:
  name: cdn-server
  labels:
    app: test4
    l2sm: "true"
  annotations:
    l2sm/networks: '[{"name": "v-network-1", "ips":["10.0.1.2/24"]}]'
spec:
  containers:
  - name: server
    command: ["/bin/ash", "-c", "ip route add 10.0.2.0/24 via 10.0.1.1 dev net1 && trap : TERM INT; sleep infinity & wait"]    
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  nodeName: test-l2sm-uc3m-polito-1
