# permissions for end users to edit overlays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: overlay-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: l2sm-kapi
    app.kubernetes.io/part-of: l2sm-kapi
    app.kubernetes.io/managed-by: kustomize
  name: overlay-editor-role
rules:
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - overlays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - l2sm.l2sm.k8s.local
  resources:
  - overlays/status
  verbs:
  - get
