apiVersion: v1
kind: Pod
metadata:
  name: ping
  labels:
    app: ping-pong
  annotations:
    l2sm/networks: '[{"name": "ping-network", "ips":["192.168.1.6/24"]}]'
spec:
  containers:
  - name: router
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  # Use this parameter if you want to place the pod in a specific node
  nodeName: l2sm1
