
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: veth6
  namespace: he-codeco-netma
  labels:
    app: l2sm
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br6",
      "mtu": 1400,
      "device": "veth6",
        "ipam": {
          "type":"static"
        }
    }'
