
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: veth10
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br10",
      "mtu": 1400,
      "device": "veth10",
        "ipam": {
          "type":"static"
        }
    }'
