# Copyright 2024 Universidad Carlos III de Madrid
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/component: server
    l2sm: "true"
    l2sm/example: quarantine
  annotations:
    l2sm/networks: '[{"name": "example-production-network", "ips": ["10.20.0.10/24"]}]'
spec:
  containers:
  - name: agnhost
    image: k8s.gcr.io/e2e-test-images/agnhost:2.21
    args:
      - netexec
      - --http-port=80
      - --udp-port=80
---
apiVersion: v1
kind: Pod
metadata:
  name: host1
  labels:
    app.kubernetes.io/name: host1
    app.kubernetes.io/component: client
    l2sm: "true"
    l2sm/example: quarantine
  annotations:
    l2sm/networks: '[{"name": "example-production-network", "ips": ["10.20.0.101/24"]}]'
spec:
  containers:
  - name: client
    image: alpine:latest
    command:
      - /bin/ash
      - -c
      - |
        while true; do
          wget -qO- --timeout=2 http://10.20.0.10:8080/ || true
          sleep 10
        done
---
apiVersion: v1
kind: Pod
metadata:
  name: host2
  labels:
    app.kubernetes.io/name: host2
    app.kubernetes.io/component: client
    l2sm: "true"
    l2sm/example: quarantine
  annotations:
    l2sm/networks: '[{"name": "example-production-network", "ips": ["10.20.0.102/24"]}]'
spec:
  containers:
  - name: client
    image: alpine:latest
    command:
      - /bin/ash
      - -c
      - |
        while true; do
          wget -qO- --timeout=2 http://10.20.0.10:8080/ || true
          sleep 12
        done

---
apiVersion: v1
kind: Pod
metadata:
  name: honeypot-server
  labels:
    l2sm: "true"
    l2sm/example: quarantine
  annotations:
    l2sm/networks: '[{"name": "example-quarantine-network", "ips": ["10.20.0.10/24"]}]'
spec:
  containers:
    - name: echo
      image: hashicorp/http-echo
      args:
      - "-text=honeypot server responds"
      - "-listen=:80"
      securityContext:
        runAsUser: 0