# Copyright 2024 Universidad Carlos III de Madrid
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: attacker
  labels:
    app.kubernetes.io/name: attacker
    app.kubernetes.io/component: client
    l2sm: "true"
    l2sm/example: quarantine
    security.l2sm/demo-role: attacker
  annotations:
    l2sm/networks: '[{"name": "example-production-network", "ips": ["10.20.0.103/24"]}]'
spec:
  containers:
  - name: attacker
    image: alpine:latest
    securityContext:
      capabilities:
        add:
          - NET_RAW
          - NET_ADMIN
    command:
      - /bin/ash
      - -c
      - |
        apk update
        apk add nmap
        sleep 2
        while true; do
          nmap -sS -Pn -p 1-1024 10.20.0.10 || true
          sleep 15
        done